export const TAG_DIMENSIONS = {
  COLOR: {
    id: 'color',
    name: 'Color',
    values: [
      'black',
      'white',
      'navy',
      'grey',
      'beige',
      'brown',
      'red',
      'orange',
      'yellow',
      'green',
      'blue',
      'purple',
      'pink',
      'neutral',
      'colorful',
    ],
  },
  STYLE: {
    id: 'style',
    name: 'Style',
    values: [
      'minimalist',
      'streetwear',
      'cottagecore',
      'bohemian',
      'preppy',
      'vintage',
      'edgy',
      'sporty',
      'romantic',
      'avant-garde',
      'classic',
      'casual',
      'formal',
    ],
  },
  CATEGORY: {
    id: 'category',
    name: 'Category',
    values: [
      'tops',
      'dresses',
      'bottoms',
      'outerwear',
      'shoes',
      'accessories',
      'activewear',
      'underwear',
    ],
  },
  MATERIAL: {
    id: 'material',
    name: 'Material',
    values: [
      'cotton',
      'linen',
      'wool',
      'silk',
      'polyester',
      'denim',
      'leather',
      'suede',
      'knit',
      'jersey',
    ],
  },
  OCCASION: {
    id: 'occasion',
    name: 'Occasion',
    values: [
      'casual',
      'work',
      'party',
      'date',
      'outdoor',
      'gym',
      'sleep',
      'beach',
    ],
  },
};

export const ONBOARDING_STYLES = [
  'Minimalist',
  'Streetwear',
  'Cottagecore',
  'Bohemian',
  'Preppy',
  'Vintage',
  'Edgy',
];

export const ONBOARDING_COLORS = [
  'Neutrals',
  'Brights',
  'Darks',
  'Pastels',
  'Warm Tones',
  'Cool Tones',
];

export const ONBOARDING_CATEGORIES = [
  'Tops',
  'Dresses',
  'Bottoms',
  'Outerwear',
  'Shoes',
  'Accessories',
];
